language: go

go:
- 1.11.5

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - export GOPATH=$GOPATH:$(pwd)
  - export PATH=$PATH:$(pwd)

script:
- publish.sh all